apiVersion: v1
kind: PersistentVolume 
metadata:
  name: pv-mongo
spec:
  storageClassName: mongo-sc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: pvc-mongo
spec:
  storageClassName: mongo-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mongo-sc
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  MONGO_INITDB_DATABASE: test
  MONGO_INITDB_ROOT_USERNAME: user
  MONGO_INITDB_ROOT_PASSWORD: password
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo-app
spec:
  selector:
    matchLabels:
      app: mongo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: mongo-app
    spec:
      containers:
      - image: mongo:3
        name: mongo-app
        ports:
        - containerPort: 27017
          protocol: TCP
        volumeMounts:
        - mountPath: /data/db
          name: mongo-volume
        envFrom:
        - configMapRef:
            name: mongo-config
      volumes:
      - name: mongo-volume
        persistentVolumeClaim:
           claimName: pvc-mongo
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-svc
spec:
  selector:
    app: mongo-app
  ports:
  - protocol: TCP
    port: 5302
    targetPort: 27017
  type: LoadBalancer